name: Luacheck

on:
  push:
    paths: ['**/*.lua']
  pull_request:
    paths: ['**/*.lua']
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    name: Run Luacheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
